version: '3'
services:
    web:
        image: nginx
        volumes:
            - "./etc/nginx/symf-base.conf:/etc/nginx/conf.d/default.template.conf"
            - "./etc/nginx/symf-base-dev.conf:/etc/nginx/conf.d/symf.base.dev.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web/app:/var/www/html"
        ports:
            - "80:80"
            - "443:443"
        env_file:
                    - ".env"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "./web/app:/var/www/html"
        links:
           - mysqldb
    composer:
        image: "composer"
        volumes:
            - "./web/app/symf-base:/app"
        command: install

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8000:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
        env_file:
                    - ".env"
    mysqldb:
        image: mysql
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
