version: '3'
services:
    web:
        image: nginx:latest
        volumes:
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template.conf"
            - "./etc/nginx/symf-base-dev.conf:/etc/nginx/conf.d/symf.base.dev.conf"
            - "./web/app:/var/www/html"
        ports:
            - "80:80"
            - "443:443"
        restart: always
        links:
            - dbsymf
    dbsymf:
        image: mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
    php:
        image: nanoninja/php-fpm
        restart: always
#        ports:
#            - "9000:9000"
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web/app:/var/www/html"
#    php:
#        image: php:7-fpm
#        volumes:
#            - "./web/app:/var/www/html"
#        links:
#            - dbsymf
#        depends_on:
#            - dbsymf
    composer:
        image: "composer"
        volumes:
            - "./web/app/symf-base:/app"
        command: install
        links:
            - php
            - dbsymf
#    myadmin:
#        image: phpmyadmin/phpmyadmin
#        ports:
#            - "8000:80"
#        environment:
#            - PMA_ARBITRARY=1
#            - PMA_HOST=${PMA_HOST}
#        restart: always
#        env_file:
#            - ".env"
#        depends_on:
#            - dbsymf
#        links:
#            - dbsymf
