imports:
    - { resource: config.yml }

nelmio_api_doc: ~

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

doctrine:
    dbal:
        connections:
            default:
                server_version: '5.7'
                driver: pdo_mysql
                host: dbsymf
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
#            test:
#                server_version: '5.7'
#                driver: pdo_mysql
#                host: dbsymf
#                port: '%database_port%'
#                dbname: '%database_name%'
#                user: '%database_user%'
#                password: '%database_password%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']


#Nelmio CORS Configuration
#nelmio_cors:
#    defaults:
#        allow_credentials: false
#        allow_origin: ['*']
#        allow_headers: ['*']
#        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#        max_age: 3600
#        hosts: []
#        origin_regex: false

##FOSRest Configuration
#fos_rest:
#    body_listener: true
#    format_listener:
#        rules:
#            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
#    param_fetcher_listener: true
#    view:
#        view_response_listener: 'force'
#        formats:
#            json: true