uz:
    resource: "@BekUZBundle/Controller"
    type:     annotation

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc