<?php

namespace Bek\UZBundle\Repository;

use Doctrine\ORM\AbstractQuery;

/**
 * UZSearchRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UZSearchRequestRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllSRRequests()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT uz FROM BekUZBundle:UZSearchRequest uz'
            )
            ->getResult(AbstractQuery::HYDRATE_ARRAY);
    }


    public function findSRequest($id)
    {
        $query = $this
            ->createQueryBuilder('uz')
            ->where('uz.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $query->getResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
