<?php

namespace Bek\UZBundle\Repository;

use Doctrine\ORM\AbstractQuery;

/**
 * UZSearchRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UZSearchRequestRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array
     */
    public function findAllSRRequests(): array
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT uz FROM BekUZBundle:UZSearchRequest uz'
            )
            ->getResult(AbstractQuery::HYDRATE_ARRAY);
    }

    /**
     * @param int $id
     * @return array
     */
    public function findSRequest(integer $id): array
    {
        $query = $this
            ->createQueryBuilder('uz')
            ->where('uz.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $query->getResult(AbstractQuery::HYDRATE_ARRAY);
    }

    public function getActualSRequests()
    {

        $query = $this
            ->createQueryBuilder('uz')
            ->where('uz.dateDep >= CURRENT_DATE()')
            ->getQuery();

        return $query->getResult(AbstractQuery::HYDRATE_ARRAY);

    }
}
