services:
    bek_uz.uzservice:
        class: Bek\UZBundle\Services\UZService
        arguments:
            $baseUrl: '%uz_base_url%'
            $lang: '%uz_lang%'
    bek_uz.uzmailer:
        class: Bek\UZBundle\Services\UZMailerService